メッセージ取得時に強制的に最大件数まで取得するかどうか
cw-shibuya/chatwork-client-gas pull request #8
Opened 2024-04-11 03:30 UTC by Minoru0420

[公式API](https://developer.chatwork.com/reference/get-rooms-room_id-messages)に準拠させました。

2024-04-11 09:49 UTC, cw-shibuya requested changes

2024-04-11 09:49 UTC, cw-shibuya commented on client.js
> +      return this.get('/rooms/' + room_id + '/messages?force' + force);
```suggestion
      return this.get('/rooms/' + room_id + '/messages?force=' + force);
```

PRありがとうございます！`=` が必要そうかなと思いました 🙏

2024-04-19 07:13 UTC, Minoru0420 commented on client.js
> +      return this.get('/rooms/' + room_id + '/messages?force' + force);
@cw-shibuya 
申し訳ございません。完全なタイポでした😆 
修正しましたのでご確認ください。

2024-08-29 01:21 UTC, cw-shibuya approved these changes
LGTM!

2024-08-29 01:21 UTC, merged